swagger: '2.0'
info:
  description: Api Documentation
  version: '1.0'
  title: Api Documentation
  termsOfService: 'urn:tos'
  contact: {}
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0'
host: 'localhost:8080'
basePath: /
tags:
  - name: Authentication
paths:
  /login:
    post:
      tags:
        - Authentication
      summary: login
      operationId: loginUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: loginForm
          description: login parameters
          required: true
          schema:
            $ref: '#/definitions/LoginForm'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/User'
        '400':
          description: BadRequest
        '401':
          description: Unauthorized
        '404':
          description: Not Found
      deprecated: false
  /sign_up:
    post:
      tags:
        - Authentication
      summary: signUp
      operationId: signUpUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: signUpForm
          description: sign up parameters
          required: true
          schema:
            $ref: '#/definitions/SignUpForm'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/User'
        '201':
          description: Created
        '400':
          description: BadRequest
      deprecated: false
  '/user/{id}':
    get:
      tags:
        - Authentication
      summary: getUser
      operationId: getUserUsingGET
      produces:
        - '*/*'
      parameters:
        - name: Authorization
          in: header
          description: Authorization token
          required: false
          type: string
        - name: id
          in: path
          description: id
          required: true
          type: string
          format: uuid
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/User'
        '401':
          description: Unauthorized
        '404':
          description: Not Found
      deprecated: false
definitions:
  LoginForm:
    type: object
    properties:
      email:
        type: string
      password:
        type: string
    title: LoginForm
  PhoneNumber:
    type: object
    properties:
      ddd:
        type: string
      number:
        type: string
    title: PhoneNumber
  SignUpForm:
    type: object
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
      phones:
        type: array
        items:
          $ref: '#/definitions/PhoneNumber'
    title: SignUpForm
  User:
    type: object
    properties:
      created:
        type: string
        format: date-time
      email:
        type: string
      lastLogin:
        type: string
        format: date-time
      modified:
        type: string
        format: date-time
      name:
        type: string
      password:
        type: string
      phones:
        type: array
        items:
          $ref: '#/definitions/PhoneNumber'
      token:
        type: string
      userId:
        type: string
        format: uuid
    title: User